"""add_users_economic_groups_table

Revision ID: 03f8c630b38e
Revises: e7a2cf919533
Create Date: 2025-02-15 08:58:52.685538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable


# revision identifiers, used by Alembic.
revision: str = '03f8c630b38e'
down_revision: Union[str, None] = 'e7a2cf919533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_economic_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('economic_group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['economic_group_id'], ['economic_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add trigger
    op.execute(get_updated_at_trigger_executable(trigger_name='users_set_updated_at_on_update', table_name='users_economic_groups'))


def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='users_set_updated_at_on_update', table_name='users_economic_groups'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_economic_groups')
    # ### end Alembic commands ###
