"""add_puma_labors_table

Revision ID: 0fe582a5bf66
Revises: d3b9b23cc53b
Create Date: 2025-02-16 19:40:52.618097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable


# revision identifiers, used by Alembic.
revision: str = '0fe582a5bf66'
down_revision: Union[str, None] = 'd3b9b23cc53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puma_labors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('labor_type', sa.String(length=50), nullable=True),
    sa.Column('labor_date', sa.Date(), nullable=False),
    sa.Column('labor_quantity_day', sa.Integer(), nullable=True),
    sa.Column('labor_area', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('seed_rate', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('grain_moisture', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_commercial_name', sa.String(length=255), nullable=True),
    sa.Column('product_dose', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('product_dose_unit', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add trigger
    op.execute(get_updated_at_trigger_executable(trigger_name='puma_labors_set_updated_at_on_update', table_name='puma_labors'))


def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='puma_labors_set_updated_at_on_update', table_name='puma_labors'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puma_labors')
    # ### end Alembic commands ###
