"""alter_puma_crop_details_table

Revision ID: 2dd46933d207
Revises: c447aaf06cce
Create Date: 2025-02-18 09:30:54.375743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd46933d207'
down_revision: Union[str, None] = 'c447aaf06cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puma_crop_details', sa.Column('crop', sa.String(length=50), nullable=True))
    op.add_column('puma_crop_details', sa.Column('season_name', sa.String(length=50), nullable=True))
    op.add_column('puma_crop_details', sa.Column('season_year', sa.String(length=4), nullable=True))
    op.alter_column('puma_crop_details', 'crop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('puma_crop_details', 'season_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puma_crop_details', 'season_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('puma_crop_details', 'crop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('puma_crop_details', 'season_year')
    op.drop_column('puma_crop_details', 'season_name')
    op.drop_column('puma_crop_details', 'crop')
    # ### end Alembic commands ###
