"""add_programs_table

Revision ID: 403cc4a096c6
Revises: ad1aec8badcd
Create Date: 2025-02-14 20:21:08.241881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable


# revision identifiers, used by Alembic.
revision: str = '403cc4a096c6'
down_revision: Union[str, None] = 'ad1aec8badcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###

    # Add trigger
    # op.execute("""
    #             CREATE TRIGGER programs_updated_at
    #             BEFORE UPDATE ON programs
    #             FOR EACH ROW
    #             EXECUTE FUNCTION trigger_set_timestamp_on_update();
    #         """)
    op.execute(get_updated_at_trigger_executable(trigger_name='programs_set_updated_at_on_update', table_name='programs'))



def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='programs_set_updated_at_on_update', table_name='programs'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    # ### end Alembic commands ###
