"""alter_puma_irrigations_table

Revision ID: 56641b339a7d
Revises: 6fe7684d3df1
Create Date: 2025-02-18 09:36:52.950938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56641b339a7d'
down_revision: Union[str, None] = '6fe7684d3df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puma_irrigations', sa.Column('crop_id', sa.Integer(), nullable=True))
    op.add_column('puma_irrigations', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('puma_irrigations', sa.Column('crop', sa.String(length=50), nullable=True))
    op.add_column('puma_irrigations', sa.Column('season_name', sa.String(length=50), nullable=True))
    op.add_column('puma_irrigations', sa.Column('season_year', sa.String(length=4), nullable=True))
    op.create_foreign_key('puma_irrigations_crop_id_fkey', 'puma_irrigations', 'crops', ['crop_id'], ['id'])
    op.create_foreign_key('puma_irrigations_season_id_fkey', 'puma_irrigations', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('puma_irrigations_season_id_fkey', 'puma_irrigations', type_='foreignkey')
    op.drop_constraint('puma_irrigations_crop_id_fkey', 'puma_irrigations', type_='foreignkey')
    op.drop_column('puma_irrigations', 'season_year')
    op.drop_column('puma_irrigations', 'season_name')
    op.drop_column('puma_irrigations', 'crop')
    op.drop_column('puma_irrigations', 'season_id')
    op.drop_column('puma_irrigations', 'crop_id')
    # ### end Alembic commands ###
