"""alter_puma_labors_table

Revision ID: 6fe7684d3df1
Revises: 2dd46933d207
Create Date: 2025-02-18 09:31:41.179288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe7684d3df1'
down_revision: Union[str, None] = '2dd46933d207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puma_labors', sa.Column('crop', sa.String(length=50), nullable=True))
    op.add_column('puma_labors', sa.Column('season_name', sa.String(length=50), nullable=True))
    op.add_column('puma_labors', sa.Column('season_year', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puma_labors', 'season_year')
    op.drop_column('puma_labors', 'season_name')
    op.drop_column('puma_labors', 'crop')
    # ### end Alembic commands ###
