"""add_farms_table

Revision ID: 8d00649976db
Revises: 03f8c630b38e
Create Date: 2025-02-15 09:12:07.914750

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable


# revision identifiers, used by Alembic.
revision: str = '8d00649976db'
down_revision: Union[str, None] = '03f8c630b38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('economic_group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['economic_group_id'], ['economic_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add trigger
    op.execute(get_updated_at_trigger_executable(trigger_name='farms_set_updated_at_on_update', table_name='farms'))


def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='farms_set_updated_at_on_update', table_name='farms'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farms')
    # ### end Alembic commands ###
