"""add_fields_table

Revision ID: 94d12bcef9b5
Revises: 8d00649976db
Create Date: 2025-02-15 09:16:29.858548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable


# revision identifiers, used by Alembic.
revision: str = '94d12bcef9b5'
down_revision: Union[str, None] = '8d00649976db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('area', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add trigger
    op.execute(get_updated_at_trigger_executable(trigger_name='fields_set_updated_at_on_update', table_name='fields'))


def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='fields_set_updated_at_on_update', table_name='fields'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields')
    # ### end Alembic commands ###
