"""add_users_table

Revision ID: ad1aec8badcd
Revises: 85f971dff08c
Create Date: 2025-02-14 20:08:00.975762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable


# revision identifiers, used by Alembic.
revision: str = 'ad1aec8badcd'
down_revision: Union[str, None] = '85f971dff08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

    # Add trigger
    op.execute(get_updated_at_trigger_executable(trigger_name='users_set_updated_at_on_update', table_name='users'))



def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='users_set_updated_at_on_update', table_name='users'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
