"""add_puma_crop_details_table

Revision ID: d3b9b23cc53b
Revises: 4b7e01fc25ca
Create Date: 2025-02-16 19:36:06.488768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, DateTime, func
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable

# revision identifiers, used by Alembic.
revision: str = 'd3b9b23cc53b'
down_revision: Union[str, None] = '4b7e01fc25ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puma_crop_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=50), nullable=True),
    sa.Column('planting_system', sa.String(length=50), nullable=True),
    sa.Column('harvest_yield', sa.Integer(), nullable=True),
    sa.Column('harvest_residue_extraction', sa.Integer(), nullable=True),
    sa.Column('harvest_burned_residues', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add trigger
    op.execute(get_updated_at_trigger_executable(trigger_name='puma_crop_details_set_updated_at_on_update', table_name='puma_crop_details'))


def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='puma_crop_details_set_updated_at_on_update', table_name='puma_crop_details'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puma_crop_details')
    # ### end Alembic commands ###
