"""add_economic_groups_table

Revision ID: e7a2cf919533
Revises: 403cc4a096c6
Create Date: 2025-02-15 08:50:55.476224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migrations.helpers import get_updated_at_trigger_executable, get_drop_trigger_executable


# revision identifiers, used by Alembic.
revision: str = 'e7a2cf919533'
down_revision: Union[str, None] = '403cc4a096c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leaf_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###

    # Add trigger
    op.execute(get_updated_at_trigger_executable(trigger_name='economic_groups_set_updated_at_on_update', table_name='economic_groups'))


def downgrade() -> None:
    op.execute(get_drop_trigger_executable(trigger_name='economic_groups_set_updated_at_on_update', table_name='economic_groups'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('economic_groups')
    # ### end Alembic commands ###
